### ISSUE TITLE
Bad performance on bottle dataset, training not converging

### ISSUE THREAD

**Issue by lorenzofilizola** [denguir/student-teacher-anomaly-detection#18]
Hello,
I am having a hard time reproducing the results of the original paper on the bottle dataset, mostly because it seems the training of the teacher network is not converging.
All training runs used the same parameters as in the README. 

![resnet](https://github.com/denguir/student-teacher-anomaly-detection/assets/65960808/5821bc54-9bbc-4686-8c2a-24b06d2a8442)
*finetuning of resnet*

![teacher](https://github.com/denguir/student-teacher-anomaly-detection/assets/65960808/13e91476-65c5-45a0-bc1d-8a381ad3bf4e)
*training of the teacher model*

![students](https://github.com/denguir/student-teacher-anomaly-detection/assets/65960808/d2579f55-d243-4745-b17a-ac5263ad168a)
*training of the student models*

**Comment by sushovanjena** [comment]
The paper is using just a pre-trained Resnet and a Teacher trained on ImageNet, where as this repo is training the Resnet on MVTec and Teacher also on MVTec.

**Comment by lorenzofilizola** [comment]
> The paper is using just a pre-trained Resnet and a Teacher trained on ImageNet, where as this repo is training the Resnet on MVTec and Teacher also on MVTec.

Thanks for the hint. By pre-training the teacher network on patches extracted from ImageNet I managed to get somewhat better results.
