### ISSUE TITLE
mvtec_dataset.sh，run error

### ISSUE THREAD

**Issue by shining-love** [denguir/student-teacher-anomaly-detection#20]
hello, I run mvtec_dataset.sh,but irt occurs error as follow:
![image](https://github.com/denguir/student-teacher-anomaly-detection/assets/49702076/981be8dd-ee1c-4411-9f96-c3f2b6682c7c)

could you help me?

**Comment by sushovanjena** [comment]
Better to download the dataset manually and run the .sh file.

**Comment by shining-love** [comment]
> Better to download the dataset manually and run the .sh file.

Yes, I did it exactly the way you mentioned above. But I cannot generate a CSV file. Can you help me generate it? Or can you give me the CSV files for all the defects?

**Comment by shining-love** [comment]
I had solved it! closed it!
