### ISSUE TITLE
what is dataset.py in mvtec_dataset.sh ?

### ISSUE THREAD

**Issue by scorpiosnow** [denguir/student-teacher-anomaly-detection#4]
python3 **dataset.py**  "$dataset" in mvtec_dataset.sh line 50

there  is no dataset.py in  the code base, but  there is a mvtec_dataset.py

what is dataset.py in mvtec_dataset.sh ?

**Comment by JesusRH97** [comment]
I guess it is just a misspelling. Dataset.py is refering to the mvtec_dataset.py so you´ll have to modify either the line where mvtec_dataset.sh refers to dataset.py or the name of the script dataset.py
